#!/bin/bash

# This is a helper script to perform builds on a Linux platform
# It handles:
# * The `nuget restore`
# * The build configuration (Debug/Release/Deploy)
# * Setting the base directory for the web content (where specified)

DEBUG_CONFIGURATION="Debug"
RELEASE_CONFIGURATION="Release"
DEPLOY_CONFIGURATION="Deploy"

SOLUTION_ROOT="$(dirname "$0")/../.."

while getopts "drDl" opt
do
  case $opt in
  d)
    configuration="$DEBUG_CONFIGURATION"
    ;;
  r)
    configuration="$RELEASE_CONFIGURATION"
    ;;
  
  D)
    configuration="$DEPLOY_CONFIGURATION"
    ;;
  
  l)
    url_root="$(realpath "${SOLUTION_ROOT}/Deployment")/Output/Documentation website/"
    ;;
  esac
done

xbuild_properties="/p:"

if [ -n "$configuration" ]
then
  xbuild_properties="${xbuild_properties}Configuration=${configuration}"
else
  xbuild_properties="${xbuild_properties}Configuration=${DEBUG_CONFIGURATION}"
fi

if [ -n "$url_root" ]
then
  xbuild_properties="${xbuild_properties};WebsiteUrlRoot=${url_root}"
fi

cd "$SOLUTION_ROOT"
nuget restore
xbuild "$xbuild_properties"