#!/bin/bash

SCRIPT_DIR="$(dirname "$0")"
SOLUTION_ROOT="${SCRIPT_DIR}/../.."
OUTPUT_ROOT="${SOLUTION_ROOT}/Deployment/Output"
NUGET_PATH="${OUTPUT_ROOT}/NuGet"

for pkg in $(find "$NUGET_PATH" -type f -name "*.nupkg")
do
  nuget push "$pkg"
done
