using System;
using NUnit.Framework;
using CraigFowler.Web.ZPT;
using CraigFowler.Web.ZPT.Metal;
using System.IO;
using CraigFowler.Web.ZPT.Tales;
using System.Xml;

namespace Test.CraigFowler.Web.ZPT.Metal
{
  [TestFixture]
  public class TestMetalElement
  {
    [Test]
    [Category("Integration")]
    public void TestGetUseMacro()
    {
      TestConfiguration config = new TestConfiguration();
      DirectoryInfo dataDir = config.GetTestDataDirectoryInfo().GetDirectories("Document Root")[0];
      ZptDocumentCollection documents = ZptDocumentCollection.CreateFromFilesystem(dataDir);
      ZptDocument masterDoc;
      ITemplateDocument underlyingDoc;
      MetalElement element, macro;
      TalesContext context = new TalesContext();
      
      context.AddDefinition("documents", documents);
      
      masterDoc = documents["macro-test-master"] as ZptDocument;
      
      Assert.IsNotNull(masterDoc, "Master document is not null");
      Assert.IsNotNull(masterDoc.GetTemplateDocument(), "Master document (underlying template document) is not null");
      
      underlyingDoc = masterDoc.GetTemplateDocument();
      
      element = (MetalElement) ((XmlDocument) underlyingDoc).GetElementsByTagName("p",
                                                                                  "http://www.w3.org/1999/xhtml")[1];
      
      Assert.IsNotNull(element, "Metal element is not null");
      
      macro = element.GetUseMacro(context);
      
      Assert.IsNotNull(macro, "Macro element is not null");
      
      Assert.AreEqual("This is text that is generated by the",
                      macro.FirstChild.Value.Trim(),
                      "Macro node has correct text value");
    }
  }
}

