// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.6.57.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CSF.Zpt.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CSF.Zpt.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ExpressionEvaluationException {
            get {
                return ResourceManager.GetString("ExpressionEvaluationException", resourceCulture);
            }
        }
        
        internal static string RenderedElementIncorrectType {
            get {
                return ResourceManager.GetString("RenderedElementIncorrectType", resourceCulture);
            }
        }
        
        internal static string MetalMacroMustBeDefined {
            get {
                return ResourceManager.GetString("MetalMacroMustBeDefined", resourceCulture);
            }
        }
        
        internal static string ModelMustNotAlreadyContainAnError {
            get {
                return ResourceManager.GetString("ModelMustNotAlreadyContainAnError", resourceCulture);
            }
        }
        
        internal static string NameMustNotBeEmptyString {
            get {
                return ResourceManager.GetString("NameMustNotBeEmptyString", resourceCulture);
            }
        }
        
        internal static string ElementMustBeCorrectType {
            get {
                return ResourceManager.GetString("ElementMustBeCorrectType", resourceCulture);
            }
        }
        
        internal static string CannotGetParentFromRootNode {
            get {
                return ResourceManager.GetString("CannotGetParentFromRootNode", resourceCulture);
            }
        }
        
        internal static string IncorrectWrappedNodeType {
            get {
                return ResourceManager.GetString("IncorrectWrappedNodeType", resourceCulture);
            }
        }
        
        internal static string ZptAttributeParsingError {
            get {
                return ResourceManager.GetString("ZptAttributeParsingError", resourceCulture);
            }
        }
        
        internal static string TalesExpressionEvaluatorNotFoundForPrefix {
            get {
                return ResourceManager.GetString("TalesExpressionEvaluatorNotFoundForPrefix", resourceCulture);
            }
        }
        
        internal static string TalesExpressionEvaluatorNotFoundByType {
            get {
                return ResourceManager.GetString("TalesExpressionEvaluatorNotFoundByType", resourceCulture);
            }
        }
        
        internal static string InvalidTalesExpressionPrefix {
            get {
                return ResourceManager.GetString("InvalidTalesExpressionPrefix", resourceCulture);
            }
        }
        
        internal static string TalRepeatExpressionMustEvaluateToIEnumerable {
            get {
                return ResourceManager.GetString("TalRepeatExpressionMustEvaluateToIEnumerable", resourceCulture);
            }
        }
        
        internal static string ContentAndReplaceAttributesCannotCoexist {
            get {
                return ResourceManager.GetString("ContentAndReplaceAttributesCannotCoexist", resourceCulture);
            }
        }
    }
}
