#!/bin/bash

solution_root="`dirname $0`/.."
binary_path="${solution_root}/CraigFowler.Web.ZPT.Builder/bin"
builder_app="${binary_path}/CraigFowler.Web.ZPT.Builder.exe"
input_path="${solution_root}/doc/documentation-website"
current_timestamp=`date "+%e %B %Y"`

output_path="$1"

if [ -n "${output_path}" ]
then
  output_option="-o ${output_path}"
else
  output_path="${input_path}/../zpt-output"
  output_option=""
fi

$builder_app -e html -c "baseUrl=http://csf-software-development.github.com/ZPT-Sharp/;timestamp=${current_timestamp}" $output_option "$input_path"
cp -r "${input_path}/static" "${output_path}"
