#!/bin/bash

SCRIPT_ROOT="$(dirname $0)"
INPUT_DIR="$SCRIPT_ROOT/Website"
IGNORED_DIR="$INPUT_DIR/Shared/"
OUTPUT_DIR="$SCRIPT_ROOT/Website-output"
DEFAULT_BASE_URL="file://$(readlink -f "$OUTPUT_DIR")/"
BASE_URL="${1:-DEFAULT_BASE_URL}"

BUILDER_PATH="$SCRIPT_ROOT/../CSF.Zpt.Cli/bin/Debug/ZptBuilder.exe"

mkdir -p "$OUTPUT_DIR"
rm -rf "$OUTPUT_DIR/*"

"$BUILDER_PATH" \
  "$INPUT_DIR/" \
  -p "*.html" \
  -o "$OUTPUT_DIR/" \
  --keyword-options "baseUrl=$BASE_URL" \
  -i "$IGNORED_DIR"

cp -r "$INPUT_DIR/css/" "$OUTPUT_DIR/"
cp -r "$INPUT_DIR/js/" "$OUTPUT_DIR/"
