// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CSF.Zpt.ExpressionEvaluators.CSharpExpressions.Host {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    internal partial class ExpressionHostBuilder : CSF.Zpt.ExpressionEvaluators.CSharpExpressions.TemplateWriterBase {
        
        public override string TransformText() {
            this.GenerationEnvironment = null;
            this.Write("\n");

foreach(var ns in GetUsingNamespaces())
{
  
            this.Write("using ");
            this.Write(this.ToStringHelper.ToStringWithCulture( ns ));
            this.Write(";");

}
foreach(var aliasedNs in GetAliasedUsingNamespaces())
{
  
            this.Write("using ");
            this.Write(this.ToStringHelper.ToStringWithCulture( aliasedNs.Item2 ));
            this.Write(" = ");
            this.Write(this.ToStringHelper.ToStringWithCulture( aliasedNs.Item1 ));
            this.Write(";");

}

            this.Write("\nnamespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture( GetClassNamespace() ));
            this.Write("\n{\n  public class ");
            this.Write(this.ToStringHelper.ToStringWithCulture( GetClassName() ));
            this.Write(" : CSF.Zpt.ExpressionEvaluators.CSharpFramework.IExpressionHost\n  {\n    #region fields\n    ");

foreach(var prop in GetDynamicProperties())
{
  
            this.Write("    private dynamic ");
            this.Write(this.ToStringHelper.ToStringWithCulture( prop ));
            this.Write(";");

}
foreach(var prop in GetTypedProperties())
{
  
            this.Write("    private ");
            this.Write(this.ToStringHelper.ToStringWithCulture( prop.Item2 ));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture( prop.Item1 ));
            this.Write(";");

}

            this.Write("\n    #endregion\n\n    #region methods\n\n    object CSF.Zpt.ExpressionEvaluators.CSharpFramework.IExpressionHost.Evaluate()\n    {\n      return ");
            this.Write(this.ToStringHelper.ToStringWithCulture( GetExpressionText() ));
            this.Write(";\n    }\n\n    void CSF.Zpt.ExpressionEvaluators.CSharpFramework.IExpressionHost.SetVariableValue(string name, object value)\n    {\n      switch(name)\n      {");

foreach(var prop in GetDynamicProperties())
{
  
            this.Write("      case \"");
            this.Write(this.ToStringHelper.ToStringWithCulture( prop ));
            this.Write("\":\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture( prop ));
            this.Write(" = value;\n        break;\n        ");

}
foreach(var prop in GetTypedProperties())
{
  
            this.Write("      case \"");
            this.Write(this.ToStringHelper.ToStringWithCulture( prop.Item1 ));
            this.Write("\":\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture( prop.Item1 ));
            this.Write(" = (");
            this.Write(this.ToStringHelper.ToStringWithCulture( prop.Item2 ));
            this.Write(") value;\n        break;\n        ");

}

            this.Write("      default:\n        var message = String.Format(\"The variable name '{0}' is not valid for this expression.\", name);\n        throw new ArgumentException(message, \"name\");\n      }\n    }\n\n    #endregion\n  }\n}\n\n");
            return this.GenerationEnvironment.ToString();
        }
        
        public override void Initialize() {
            base.Initialize();
        }
    }
}
