#!/bin/bash

SCRIPT_ROOT="$(dirname $0)"

# The following paths are all relative to the solution root
OUTPUT_PATH="obj/Release/Doxygen-output"
CONFIG_PATH="Doxygen.cfg"
LATEX_PATH="${OUTPUT_PATH}/latex"

cd "$SCRIPT_ROOT"

rm -rf "$OUTPUT_PATH"
mkdir -p "$OUTPUT_PATH"

doxygen "$CONFIG_PATH"

original_path="$(pwd)"

cd "${LATEX_PATH}/"
pdflatex refman.tex
cd "$original_path"

mv "${LATEX_PATH}/refman.pdf" "${OUTPUT_PATH}/ZPT-Sharp API documentation.pdf"