#!/bin/bash

# -----------------------
# Command-line parameters
BASE_URL="$1"
VERSION="$2"
# -----------------------

# Script begins here
SCRIPT_ROOT="$(dirname $0)"
INPUT_DIR="$SCRIPT_ROOT/Website"
IGNORED_DIR="$INPUT_DIR/Shared/"
OUTPUT_DIR="$SCRIPT_ROOT/obj/Release/Doc-website"
DEFAULT_BASE_URL="file://$(readlink -f "$OUTPUT_DIR")/"
BASE_URL="${BASE_URL:-$DEFAULT_BASE_URL}"
CURRENT_DATE="$(date +%F)"
VERSION="${VERSION:-unknown}"

BUILDER_PATH="$SCRIPT_ROOT/../CSF.Zpt.Cli/bin/Release/ZptBuilder.exe"

if [ ! -e "$BUILDER_PATH" ]
then
  echo "The ZptBuilder.exe application must exist - have you forgotten to perform a release-mode build?" >&2
  exit 1
fi

mkdir -p "$OUTPUT_DIR"
rm -rf "$OUTPUT_DIR/*"

"$BUILDER_PATH" \
  "$INPUT_DIR/" \
  -p "*.html" \
  -o "$OUTPUT_DIR/" \
  --keyword-options "baseUrl=$BASE_URL;buildDate=$CURRENT_DATE;version=$VERSION" \
  -i "$IGNORED_DIR"

cp -r "$INPUT_DIR/css/" "$OUTPUT_DIR/"
cp -r "$INPUT_DIR/js/" "$OUTPUT_DIR/"
