#!/bin/bash
SCRIPT_ROOT="$(dirname $0)"
INPUT_FILENAME="../ZptBuilder.1"
OUTPUT_FILENAME="../bin/Release/Doc/ZptBuilder.MANUAL.txt"
DOCUMENT_CHARACTER_WIDTH="80"

mkdir -p "$(dirname "${SCRIPT_ROOT}/${OUTPUT_FILENAME}")"

COLUMNS="$DOCUMENT_CHARACTER_WIDTH" man --nh \
  -l "${SCRIPT_ROOT}/${INPUT_FILENAME}" \
  > "${SCRIPT_ROOT}/${OUTPUT_FILENAME}"