// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CSF.Zpt.Cli.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CSF.Zpt.Cli.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string OptionsParsingError {
            get {
                return ResourceManager.GetString("OptionsParsingError", resourceCulture);
            }
        }
        
        internal static string HtmlAndXmlModesMutuallyExclusive {
            get {
                return ResourceManager.GetString("HtmlAndXmlModesMutuallyExclusive", resourceCulture);
            }
        }
        
        internal static string InvalidInputFile {
            get {
                return ResourceManager.GetString("InvalidInputFile", resourceCulture);
            }
        }
        
        internal static string BatchOptionsCreationExceptionMessage {
            get {
                return ResourceManager.GetString("BatchOptionsCreationExceptionMessage", resourceCulture);
            }
        }
        
        internal static string RenderingOptionsCreationExceptionMessage {
            get {
                return ResourceManager.GetString("RenderingOptionsCreationExceptionMessage", resourceCulture);
            }
        }
    }
}
