// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.6.57.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CSF.Zpt.Cli.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CSF.Zpt.Cli.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: ZptBuilder.exe [options] [inputs]
        ///
        ///Selected options:
        ///
        ///--help, -h
        ///    Display this usage statement and exit
        ///
        ///--html,-t
        ///    Force HTML mode
        ///
        ///--xml,-x
        ///    Force XML mode
        ///
        ///--no-xml-declaration
        ///    Omit XML declaration when rendering XML
        ///
        ///--input-filename-pattern=PATTERN,-p
        ///    Search pattern for files to render when
        ///    the input is a directory path
        ///
        ///--output=LOCATION,-o
        ///    Saves output to the specified path
        ///
        ///--output-filename-extension=EXT,-E
        ///    The extension for output file na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UsageStatement {
            get {
                return ResourceManager.GetString("UsageStatement", resourceCulture);
            }
        }
    }
}
